import type { Span, TraceDetail } from "@/lib/types";

const CS_ID = "trace_cs_001";
const RESEARCH_ID = "trace_research_001";

function span(
  partial: Omit<Span, "run_id" | "framework" | "attributes" | "error_message"> &
    Partial<
      Pick<
        Span,
        | "run_id"
        | "framework"
        | "attributes"
        | "error_message"
        | "model"
        | "prompt_tokens"
        | "completion_tokens"
        | "total_tokens"
        | "cost_usd"
      >
    >,
): Span {
  return {
    run_id: partial.run_id ?? "run_demo",
    framework: partial.framework ?? "openai",
    attributes: partial.attributes ?? {},
    error_message: partial.error_message ?? null,
    ...partial,
  };
}

export const customerServiceTraceDetail: TraceDetail = {
  trace_id: CS_ID,
  run_id: "2bb8bf47d68e8dd5c4e2ea9ea820ab52",
  meta: {
    name: "Customer service",
    version: "v0.4.21",
    model: "gpt-4o-mini",
    duration_ms: 65000,
    total_cost_usd: 0.0124,
    llm_calls: 3,
    tool_calls: 1,
    errors: 0,
    total_tokens: 2251,
    tags: ["openai-agents", "veritrix-example", "customer-service-agent"],
    start_time: "2026-07-10T14:25:18.000Z",
  },
  agents: [
    {
      name: "Triage Agent",
      handoffs: ["FAQ Agent", "Seat Booking Agent"],
      tools: [],
    },
    {
      name: "FAQ Agent",
      handoffs: ["Triage Agent"],
      tools: ["faq_lookup_tool"],
    },
  ],
  spans: [
    // Turn 1 — early cluster (left side of waterfall)
    span({
      trace_id: CS_ID,
      span_id: "cs_root_1",
      parent_span_id: null,
      agent_id: "customer_service",
      agent_name: "Customer service",
      span_type: "other",
      start_time: "2026-07-10T14:25:18.000Z",
      end_time: "2026-07-10T14:25:24.500Z",
      duration_ms: 6500,
      status: "ok",
      input_preview: "",
      output_preview: "",
      attributes: { span_name: "Customer service" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_workflow_1",
      parent_span_id: "cs_root_1",
      agent_id: "customer_service",
      agent_name: "Agent workflow",
      span_type: "other",
      start_time: "2026-07-10T14:25:18.100Z",
      end_time: "2026-07-10T14:25:24.400Z",
      duration_ms: 6300,
      status: "ok",
      input_preview: "",
      output_preview: "",
      attributes: { span_name: "Agent workflow" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_triage_1",
      parent_span_id: "cs_workflow_1",
      agent_id: "triage_agent",
      agent_name: "Triage Agent",
      span_type: "agent",
      start_time: "2026-07-10T14:25:18.200Z",
      end_time: "2026-07-10T14:25:22.500Z",
      duration_ms: 4300,
      status: "ok",
      input_preview: "Route this request to the right specialist.",
      output_preview: "Handing off to FAQ Agent",
      attributes: { span_name: "Triage Agent" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_turn_1",
      parent_span_id: "cs_triage_1",
      agent_id: "triage_agent",
      agent_name: "turn",
      span_type: "other",
      start_time: "2026-07-10T14:25:18.300Z",
      end_time: "2026-07-10T14:25:21.800Z",
      duration_ms: 3500,
      status: "ok",
      input_preview: "",
      output_preview: "",
      attributes: { span_name: "turn" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_llm_1",
      parent_span_id: "cs_turn_1",
      agent_id: "triage_agent",
      agent_name: "response",
      span_type: "llm",
      start_time: "2026-07-10T14:25:18.500Z",
      end_time: "2026-07-10T14:25:21.200Z",
      duration_ms: 2700,
      status: "ok",
      model: "gpt-4o-mini",
      prompt_tokens: 228,
      completion_tokens: 42,
      total_tokens: 270,
      cost_usd: 0.0004,
      input_preview: "jyou",
      output_preview: "I'm not sure what you mean by 'jyou",
      attributes: { span_name: "I'm not sure what you mean by 'jyou" },
    }),

    // Turn 2 — later cluster (right side of waterfall)
    span({
      trace_id: CS_ID,
      span_id: "cs_root_2",
      parent_span_id: null,
      agent_id: "customer_service",
      agent_name: "Customer service",
      span_type: "other",
      start_time: "2026-07-10T14:25:48.000Z",
      end_time: "2026-07-10T14:26:23.000Z",
      duration_ms: 35000,
      status: "ok",
      input_preview: "",
      output_preview: "",
      attributes: { span_name: "Customer service" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_workflow_2",
      parent_span_id: "cs_root_2",
      agent_id: "customer_service",
      agent_name: "Agent workflow",
      span_type: "other",
      start_time: "2026-07-10T14:25:48.100Z",
      end_time: "2026-07-10T14:26:22.800Z",
      duration_ms: 34700,
      status: "ok",
      input_preview: "",
      output_preview: "",
      attributes: { span_name: "Agent workflow" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_triage_2",
      parent_span_id: "cs_workflow_2",
      agent_id: "triage_agent",
      agent_name: "Triage Agent",
      span_type: "agent",
      start_time: "2026-07-10T14:25:48.200Z",
      end_time: "2026-07-10T14:25:52.000Z",
      duration_ms: 3800,
      status: "ok",
      input_preview: "Clarify the customer request.",
      output_preview: "Sure — what can I help with?",
      attributes: { span_name: "Triage Agent" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_turn_2",
      parent_span_id: "cs_triage_2",
      agent_id: "triage_agent",
      agent_name: "turn",
      span_type: "other",
      start_time: "2026-07-10T14:25:48.300Z",
      end_time: "2026-07-10T14:25:51.500Z",
      duration_ms: 3200,
      status: "ok",
      input_preview: "",
      output_preview: "",
      attributes: { span_name: "turn" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_llm_2",
      parent_span_id: "cs_turn_2",
      agent_id: "triage_agent",
      agent_name: "response",
      span_type: "llm",
      start_time: "2026-07-10T14:25:48.500Z",
      end_time: "2026-07-10T14:25:51.200Z",
      duration_ms: 2700,
      status: "ok",
      model: "gpt-4o-mini",
      prompt_tokens: 180,
      completion_tokens: 36,
      total_tokens: 216,
      cost_usd: 0.0003,
      input_preview: "help",
      output_preview: "Sure — what can I help with?",
      attributes: { span_name: "Sure — what" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_faq",
      parent_span_id: "cs_workflow_2",
      agent_id: "faq_agent",
      agent_name: "FAQ Agent",
      span_type: "agent",
      start_time: "2026-07-10T14:25:52.200Z",
      end_time: "2026-07-10T14:26:22.000Z",
      duration_ms: 29800,
      status: "ok",
      input_preview: "Look up baggage allowance for economy flights.",
      output_preview: "Economy passengers may bring one carry-on up to 7kg.",
      attributes: { span_name: "FAQ Agent" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_faq_tool",
      parent_span_id: "cs_faq",
      agent_id: "faq_agent",
      agent_name: "faq_lookup_tool",
      span_type: "tool",
      start_time: "2026-07-10T14:25:52.500Z",
      end_time: "2026-07-10T14:25:54.000Z",
      duration_ms: 1500,
      status: "ok",
      input_preview: '{"query":"baggage allowance economy"}',
      output_preview: '{"answer":"One carry-on up to 7kg"}',
      attributes: { span_name: "faq_lookup_tool" },
    }),
    span({
      trace_id: CS_ID,
      span_id: "cs_faq_llm",
      parent_span_id: "cs_faq",
      agent_id: "faq_agent",
      agent_name: "response",
      span_type: "llm",
      start_time: "2026-07-10T14:25:54.200Z",
      end_time: "2026-07-10T14:26:21.500Z",
      duration_ms: 27300,
      status: "ok",
      model: "gpt-4o-mini",
      prompt_tokens: 812,
      completion_tokens: 186,
      total_tokens: 998,
      cost_usd: 0.0018,
      input_preview: "Answer the customer using the FAQ tool result...",
      output_preview: "Economy passengers may bring one carry-on bag up to 7kg.",
      attributes: { span_name: "response" },
    }),
  ],
};

export const researchTraceDetail: TraceDetail = {
  trace_id: RESEARCH_ID,
  run_id: "run_research_agent_42",
  meta: {
    name: "Research Agent",
    version: "v0.1.0",
    model: "gpt-4o-mini",
    duration_ms: 8420,
    total_cost_usd: 0.0024,
    llm_calls: 1,
    tool_calls: 1,
    errors: 1,
    total_tokens: 512,
    tags: ["crewai", "research"],
    start_time: "2026-07-10T10:14:22.000Z",
  },
  agents: [
    {
      name: "Research Agent",
      handoffs: [],
      tools: ["web_search"],
    },
  ],
  spans: [
    span({
      trace_id: RESEARCH_ID,
      span_id: "span_1",
      parent_span_id: null,
      agent_id: "agent_research",
      agent_name: "Research Agent",
      framework: "crewai",
      span_type: "agent",
      start_time: "2026-07-10T10:14:22.000Z",
      end_time: "2026-07-10T10:14:30.420Z",
      duration_ms: 8420,
      status: "error",
      error_message: "Tool call failed: web_search timeout after 30s",
      input_preview: "Research latest multi-agent observability patterns",
      output_preview: "Partial results before tool failure",
    }),
    span({
      trace_id: RESEARCH_ID,
      span_id: "span_2",
      parent_span_id: "span_1",
      agent_id: "agent_research",
      agent_name: "web_search",
      framework: "crewai",
      span_type: "tool",
      start_time: "2026-07-10T10:14:23.000Z",
      end_time: "2026-07-10T10:14:28.000Z",
      duration_ms: 5000,
      status: "error",
      error_message: "web_search timeout after 30s",
      input_preview: '{"query":"multi-agent observability 2026"}',
      output_preview: "",
    }),
    span({
      trace_id: RESEARCH_ID,
      span_id: "span_3",
      parent_span_id: "span_1",
      agent_id: "agent_research",
      agent_name: "llm",
      framework: "crewai",
      span_type: "llm",
      start_time: "2026-07-10T10:14:28.100Z",
      end_time: "2026-07-10T10:14:30.200Z",
      duration_ms: 2100,
      status: "ok",
      model: "gpt-4o-mini",
      prompt_tokens: 320,
      completion_tokens: 90,
      total_tokens: 410,
      cost_usd: 0.0009,
      input_preview: "Summarize what we know so far...",
      output_preview: "Unable to finish research due to tool timeout.",
    }),
  ],
};

const TRACE_DETAILS: Record<string, TraceDetail> = {
  [CS_ID]: customerServiceTraceDetail,
  [RESEARCH_ID]: researchTraceDetail,
};

export function getMockTraceDetail(traceId: string): TraceDetail | null {
  return TRACE_DETAILS[traceId] ?? customerServiceTraceDetail;
}
